#+title: Code and Data for Manuscript: 'Expanded plant hydraulic diversity with intensified precipitation'
#+author: Jacob I. Levine

* Description
This repository accompanies the manuscript titled /Expanded plant hydraulic diversity with intensified preciptitation/ submitted to /Science/ for review. The repository contains the scripts and data used to replicate the analyses in that paper.

The repository is organized as follows:
+ =/code= contains all scripts used to conduct the empirical and theoretical analyses
  - =/figures= contains scripts to generate the figures presented in both the main text and supplement.
  - =/simulator= contains scripts used to simulate the dynamics from the theoretical model of competition for water and light among species with differing hydraulic traits. These scripts are adapted from [[https://doi.org/10.1002/ecm.70012][Levine et al. 2025, Ecological Monographs.]]
  - scripts to process raw data and conduct statistical analysis are found in the main =/code= directory and are numbered in the order they should be run to replicate the analyses in the manuscript
+ =/data= contains all data used in the main statistical and sensitivity analyses, with two exceptions due to file size: the reanalysis data, which are publicly available at [[https://doi.org/10.48364/ISIMIP.886955]]; and the growing season data, which can be downloaded from [[https://www.doi.org/10.16904/envidat.332]].
+ =/figures= contains all output figure files, as well as Adobe Illustrator files used to polish the initial outputs.

* Requirements
To run the code, users must have updated distributions of both R (version >= 4.4.1) and julia (version >= 1.11.1). The =Manifest.toml= and =Project.toml= files contain all package version information for julia to ensure replicability. In general, statistical analyses were conducted in R, whereas theoretical and computational analyses were conducted in julia, for speed.

* Authorship
All the scripts contained in this database were written by Jacob I. Levine (@jsilevine). The manuscript was written by Jacob I. Levine, Jonathan M. Levine, William R. L. Anderegg, and Stephen W. Pacala. While Jacob wrote the scripts, each coauthor contributed to the ideas and workflows contained in this repository.

* Contact Information
For questions or issues, please contact:

+ Name: *Jacob Levine*
+ Email: ~jacob.levine@utah.edu~
+ GitHub: ~[[https://github.com/jsilevine]]~
+ Website: [[levine-ecology.com]]
